# -*- coding: utf-8 -*-
"""HW2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1cZPXtxBIz2Bl4SluMwHNw534q_tszfgv
"""

!git clone https://github.com/PeizeSun/OneNet.git

cd OneNet

"""#  installing torchvison according to your cuda version"""

!nvcc --version

pip install torch==1.7.1+cu101 torchvision==0.8.2+cu101 torchaudio===0.7.2 -f https://download.pytorch.org/whl/torch_stable.html

"""# restart runtime after installing"""

!pip install pyyaml==5.1 pycocotools>=2.0.1

import torch, torchvision
print(torch.__version__, torch.cuda.is_available())

"""# install onenet"""

!python setup.py build develop

from google.colab import drive
drive.mount('/content/drive')

"""# link coco datset to OneNet dateset folder
## download COCO dataset and then link the folder with OneNet
"""

!mkdir -p datasets/coco
!ln -s /content/drive/MyDrive/Hw2/COCO/2017/annotations datasets/coco/annotations
!ln -s /content/drive/MyDrive/Hw2/COCO/2017/train2017 datasets/coco/train2017
!ln -s /content/drive/MyDrive/Hw2/COCO/2017/val2017 datasets/coco/val2017

pip install -U iopath

"""# train ONeNet"""

!python projects/OneNet/train_net.py --num-gpus 1 \
    --config-file projects/OneNet/configs/onenet.res18.dcn.yaml

"""# Evaluate"""

!python projects/OneNet/train_net.py --num-gpus 1 \
    --config-file projects/OneNet/configs/onenet.res18.dcn.yaml \
    --eval-only MODEL.WEIGHTS /content/drive/MyDrive/Hw2/model_onenet_r18dcn.pth

"""# Visualize
install opencv additinoally for visualize
"""

!python demo/demo.py\
    --config-file projects/OneNet/configs/onenet.res18.dcn.yaml \
    --input /content/drive/MyDrive/Hw2/COCO/2017/test2017/000000000229.jpg --output /content/drive/MyDrive/Hw2/result --confidence-threshold 0.4 \
    --opts MODEL.WEIGHTS /content/drive/MyDrive/Hw2/model_onenet_r18dcn.pth